Hello Microverse PR
carlosisraelsilva/Hello-Microverse pull request #1
Opened 2023-01-10 21:24 UTC by carlosisraelsilva

I accomplished the following tasks as part of this project milestone:

- Added the index.html and style.css files in a separate commit. 
- Added the README.md file updated
- Confirmed that no linter error was present

2023-01-10 21:39 UTC, jerryowusu requested changes
Hi @carlosisraelsilva , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![no-we-were-so-close-pauline-turner-brooks](https://user-images.githubusercontent.com/65233860/211667800-62ec911d-9802-40a3-b85b-e6f471684987.gif)


## Highlights
All linters are passing :heavy_check_mark: 
Great effort so far :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 21:39 UTC, jerryowusu commented on README.md
> +- This project is [MIT](./LICENSE) licensed.
Your readme file is missing certain headers/sections like the `Key Features` and `Future Features`. Kindly ensure that all features/sections of the Microverse [readme template](https://github.com/microverseinc/readme-template) is present and customized according to your credentials. :pray:

2023-01-11 00:20 UTC, KanzaTahreem requested changes
# Changes Required 🔁
Hi @carlosisraelsilva 

Good job implementing the changes suggested by previous reviewer! I know you worked hard to implement this project, I really appreciate the effort you put in! 

**_However, I did notice a few areas that still need some changes that will further enhance the quality of your README._**  But you are almost there!  💪.

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

- Well done so far for editing README
- Descriptive PR
- Correct Linters

However, there is always room for improvement.

## Required Changes ♻

> _Please keep in mind that your long hours of work is appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄_

Please make sure to follow the [README template](https://github.com/microverseinc/readme-template) for creating a high quality and professional README ✌ For more clarity, you can visit 👉 [this README](https://github.com/KanzaTahreem/OOP-School-Library).

_Please check the comments under the review._

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Please check the comments under the review._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**_Reviewed By [Kanza Tahreem](https://github.com/KanzaTahreem)_**

2023-01-11 00:20 UTC, KanzaTahreem commented on README.md
> +
[OPTIONAL] I think it would be better if you follow the [readme template](https://github.com/microverseinc/readme-template) for creating your README 📝. For more clarity, you can visit [this README](https://github.com/KanzaTahreem/OOP-School-Library)

### _Your README before_ 👇
![image](https://user-images.githubusercontent.com/106119105/211684642-7a39d67a-7134-4381-808b-22ed8de04fe7.png)

### _Your README now_ 👇
![image](https://user-images.githubusercontent.com/106119105/211684693-6b154ffc-7ba0-428e-a22c-edecf23fcbf8.png)

### _Microverse readme template_ 👇
![image](https://user-images.githubusercontent.com/106119105/211684744-6e2d4052-59d1-46fe-9754-17ce0f830a56.png)

2023-01-11 00:20 UTC, KanzaTahreem commented on README.md
> +
Great job implementing two `headers/sections` (`key features` and `future features`). Please make sure to add all sections/headers as suggested by previous reviewer by following README [template](https://github.com/microverseinc/readme-template)  📑

### _Your README before_ 👇
![image](https://user-images.githubusercontent.com/106119105/211685178-42369fff-c9f1-425c-95ab-a703f7e0c2c1.png)

### _Your README now_ 👇
![image](https://user-images.githubusercontent.com/106119105/211685255-73d88af6-3e6d-4828-ab08-4febf8db71da.png)

### _Microverse README template_ 👇
![image](https://user-images.githubusercontent.com/106119105/211685294-7ba264dd-1720-418d-a924-fe8d60ecabba.png)

2023-01-11 00:20 UTC, KanzaTahreem commented on README.md
> +<<<<<<< HEAD
- [ ] Please make sure to remove `<<<<<<< HEAD` from your README. A high quality and professional README makes it easier to navigate and creates a great user experience ✌

### _Your README before 👇_
![image](https://user-images.githubusercontent.com/106119105/211686362-6f528a8a-7dd3-4d6f-8cb0-de1d1ed004a7.png)

### _Your README now_
![image](https://user-images.githubusercontent.com/106119105/211686461-e9b37be0-cce0-417a-b29a-87da71b87884.png)

2023-01-11 00:20 UTC, KanzaTahreem commented on README.md
> +<<<<<<< HEAD
- [OPTIONAL] I think it would be better if you remove the `<<<<<<< HEAD` from your README to make it look more professional. A high quality and professional README create a great user experience 😃

2023-01-11 00:20 UTC, KanzaTahreem commented on README.md
> +
[OPTIONAL] Great job implementing the future feature 👍 I think it would be better if you remove `**[new_feature_1]**` and `**[new_feature_2]**` as these are there for your guidance 😃

2023-01-11 09:00 UTC, Debas-31 approved these changes
> ## Hi @carlosisraelsilva  :wave:, 

# Status: Approved :heavy_check_mark: 

Great work on making the changes requested by a previous reviewer. Your project is complete !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/fYlennPcKut8gjKOZD/giphy.gif"/>

## Highlights
- Linters setup :heavy_check_mark:
- GitHub flow :heavy_check_mark: 
- PR title, PR summary, and README file :heavy_check_mark: 
- Commit message :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 09:22 UTC, merged